apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: sample-site-du-subscription
  namespace: sample-site-du-subscription
  labels:
    app: sample-site-du-subscription
  annotations:
    apps.open-cluster-management.io/git-path: manifests/sites/sample_site_du
    apps.open-cluster-management.io/git-branch: cnfde6
spec:
  channel: sample-site-du-subscription/sample-site-du-subscription 
  placement:
    local: true
