apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ran-subscription
  namespace: ran-subscriptions
  labels:
    app: ran-subscription
  annotations:
    apps.open-cluster-management.io/git-path: manifests/base
    apps.open-cluster-management.io/git-branch: cnfde6
spec:
  channel: ran-subscriptions/ran-subscription 
  placement:
    local: true
