apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: du-subscription
  namespace: du-subscriptions
  labels:
    app: du-subscription
  annotations:
    apps.open-cluster-management.io/git-path: manifests/function/du
    apps.open-cluster-management.io/git-branch: cnfde6
spec:
  channel: du-subscriptions/du-subscription 
  placement:
    local: true
