apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: cnfde6-site-subscription
  namespace: cnfde6-site-subscription
  labels:
    app: cnfde6-site-subscription
  annotations:
    apps.open-cluster-management.io/git-path: manifests/sites/cnfde6_site
    apps.open-cluster-management.io/git-branch: main
spec:
  channel: cnfde6-site-subscription/cnfde6-site-subscription 
  placement:
    local: true
